const vowels = [
  { title: "Sheva", dataChar: "ְ", dataKey: "Digit1", letter: "ְ", qwertyLetter: "1" },
  { title: "Hataf Segol", dataChar: "ֱ", dataKey: "Digit2", letter: "ֱ", qwertyLetter: "2" },
  { title: "Hataf Patah", dataChar: "ֲ", dataKey: "Digit3", letter: "ֲ", qwertyLetter: "3" },
  { title: "Hataf Qamats", dataChar: "ֳ", dataKey: "Digit4", letter: "ֳ", qwertyLetter: "4" },
  { title: "Hiriq", dataChar: "ִ", dataKey: "Digit5", letter: "ִ", qwertyLetter: "5" },
  { title: "Tsere", dataChar: "ֵ", dataKey: "Digit6", letter: "ֵ", qwertyLetter: "6" },
  { title: "Segol", dataChar: "ֶ", dataKey: "Digit7", letter: "ֶ", qwertyLetter: "7" },
  { title: "Patah", dataChar: "ַ", dataKey: "Digit8", letter: "ַ", qwertyLetter: "8" },
  { title: "Qamats", dataChar: "ָ", dataKey: "Digit9", letter: "ָ", qwertyLetter: "9" },
  { title: "Holam", dataChar: "ֹ", dataKey: "Digit0", letter: "ֹ", qwertyLetter: "0" },
  { title: "Dagesh or Mapiq", dataChar: "ּ", dataKey: "Minus", letter: "ּ", qwertyLetter: "-" },
  { title: "Sin Dot", dataChar: "ׂ", dataKey: "Equal", letter: "ׂ", qwertyLetter: "=" },
]

const consonants = [
  { title: "Kuf", dataChar: "ק", dataKey: "KeyQ", letter: "ק", qwertyLetter: "Q" },
  { title: "Resh", dataChar: "ר", dataKey: "KeyW", letter: "ר", qwertyLetter: "W" },
  { title: "Alef", dataChar: "א", dataKey: "KeyE", letter: "א", qwertyLetter: "E" },
  { title: "Tet", dataChar: "ט", dataKey: "KeyR", letter: "ט", qwertyLetter: "R" },
  { title: "Vav", dataChar: "ו", dataKey: "KeyT", letter: "ו", qwertyLetter: "T" },
  { title: "Final Nun", dataChar: "ן", dataKey: "KeyY", letter: "ן", qwertyLetter: "Y" },
  { title: "Final Mem", dataChar: "ם", dataKey: "KeyU", letter: "ם", qwertyLetter: "U" },
  { title: "Pe", dataChar: "פ", dataKey: "KeyI", letter: "פ", qwertyLetter: "I" },
  { title: "Shin", dataChar: "ש", dataKey: "KeyO", letter: "ש", qwertyLetter: "O" },
  { title: "Dalet", dataChar: "ד", dataKey: "KeyP", letter: "ד", qwertyLetter: "P" },
  { title: "Gimel", dataChar: "ג", dataKey: "KeyA", letter: "ג", qwertyLetter: "A" },
  { title: "Kaf", dataChar: "כ", dataKey: "KeyS", letter: "כ", qwertyLetter: "S" },
  { title: "Ayin", dataChar: "ע", dataKey: "KeyD", letter: "ע", qwertyLetter: "D" },
  { title: "Yod", dataChar: "י", dataKey: "KeyF", letter: "י", qwertyLetter: "F" },
  { title: "Het", dataChar: "ח", dataKey: "KeyG", letter: "ח", qwertyLetter: "G" },
  { title: "Lamed", dataChar: "ל", dataKey: "KeyH", letter: "ל", qwertyLetter: "H" },
  { title: "Final Kaf", dataChar: "ך", dataKey: "KeyJ", letter: "ך", qwertyLetter: "J" },
  { title: "Final Pe", dataChar: "ף", dataKey: "KeyK", letter: "ף", qwertyLetter: "K" },
  { title: "Zayin", dataChar: "ז", dataKey: "KeyL", letter: "ז", qwertyLetter: "L" },
  { title: "Samekh", dataChar: "ס", dataKey: "Semicolon", letter: "ס", qwertyLetter: ";" },
  { title: "Bet", dataChar: "ב", dataKey: "KeyZ", letter: "ב", qwertyLetter: "Z" },
  { title: "He", dataChar: "ה", dataKey: "KeyX", letter: "ה", qwertyLetter: "X" },
  { title: "Nun", dataChar: "נ", dataKey: "KeyC", letter: "נ", qwertyLetter: "C" },
  { title: "Mem", dataChar: "מ", dataKey: "KeyV", letter: "מ", qwertyLetter: "V" },
  { title: "Tsadi", dataChar: "צ", dataKey: "KeyB", letter: "צ", qwertyLetter: "B" },
  { title: "Tav", dataChar: "ת", dataKey: "KeyN", letter: "ת", qwertyLetter: "N" },
  { title: "Final Tsadi", dataChar: "ץ", dataKey: "KeyM", letter: "ץ", qwertyLetter: "M" },
]

export const standardLayout = { vowels: vowels, consonants: consonants }
