export const paleoLayout = {
  Digit1: { title: "blank", letter: "blank", qwertyLetter: "1" },
  Digit2: { title: "blank", letter: "blank", qwertyLetter: "2" },
  Digit3: { title: "blank", letter: "blank", qwertyLetter: "3" },
  Digit4: { title: "blank", letter: "blank", qwertyLetter: "4" },
  Digit5: { title: "blank", letter: "blank", qwertyLetter: "5" },
  Digit6: { title: "blank", letter: "blank", qwertyLetter: "6" },
  Digit7: { title: "blank", letter: "blank", qwertyLetter: "7" },
  Digit8: { title: "blank", letter: "blank", qwertyLetter: "8" },
  Digit9: { title: "blank", letter: "blank", qwertyLetter: "9" },
  Digit0: { title: "blank", letter: "blank", qwertyLetter: "0" },
  Minus: { title: "blank", letter: "blank", qwertyLetter: "-" },
  Equal: { title: "blank", letter: "blank", qwertyLetter: "=" },

  KeyQ: { title: "blank", letter: "blank", qwertyLetter: "Q" },
  KeyW: { title: "blank", letter: "blank", qwertyLetter: "W" },
  KeyE: { title: "Qoph", letter: "𐤒", qwertyLetter: "E" },
  KeyR: { title: "Resh", letter: "𐤓", qwertyLetter: "R" },
  KeyT: { title: "Aleph", letter: "𐤀", qwertyLetter: "T" },
  KeyY: { title: "Tet", letter: "𐤈", qwertyLetter: "Y" },
  KeyU: { title: "Waw", letter: "𐤅", qwertyLetter: "U" },
  KeyI: { title: "Taw", letter: "𐤕", qwertyLetter: "I" },
  KeyO: { title: "blank", letter: "blank", qwertyLetter: "O" },
  KeyP: { title: "Peh", letter: "𐤐", qwertyLetter: "P" },

  KeyA: { title: "Shin", letter: "𐤔", qwertyLetter: "A" },
  KeyS: { title: "Dalet", letter: "𐤃", qwertyLetter: "S" },
  KeyD: { title: "Gimel", letter: "𐤂", qwertyLetter: "D" },
  KeyF: { title: "Kaph", letter: "𐤊", qwertyLetter: "F" },
  KeyG: { title: "Ayin", letter: "𐤏", qwertyLetter: "G" },
  KeyH: { title: "Yod", letter: "𐤉", qwertyLetter: "H" },
  KeyJ: { title: "Heth", letter: "𐤇", qwertyLetter: "J" },
  KeyK: { title: "Lamedh", letter: "𐤋", qwertyLetter: "K" },
  KeyL: { title: "blank", letter: "blank", qwertyLetter: "L" },
  Semicolon: { title: "blank", letter: "blank", qwertyLetter: ";" },

  KeyZ: { title: "Zayin", letter: "𐤆", qwertyLetter: "Z" },
  KeyX: { title: "Samekh", letter: "𐤎", qwertyLetter: "X" },
  KeyC: { title: "Bet", letter: "𐤁", qwertyLetter: "C" },
  KeyV: { title: "He", letter: "𐤄", qwertyLetter: "V" },
  KeyB: { title: "Nun", letter: "𐤍", qwertyLetter: "B" },
  KeyN: { title: "Mem", letter: "𐤌", qwertyLetter: "N" },
  KeyM: { title: "Tsade", letter: "𐤑", qwertyLetter: "M" },
};
