export const standardFlatLayout = {
  Digit1: { title: "Sheva", letter: "ְ", qwertyLetter: "1" },
  Digit2: { title: "Hataf Segol", letter: "ֱ", qwertyLetter: "2" },
  Digit3: { title: "Hataf Patah", letter: "ֲ", qwertyLetter: "3" },
  Digit4: { title: "Hataf Qamats", letter: "ֳ", qwertyLetter: "4" },
  Digit5: { title: "Hiriq", letter: "ִ", qwertyLetter: "5" },
  Digit6: { title: "Tsere", letter: "ֵ", qwertyLetter: "6" },
  Digit7: { title: "Segol", letter: "ֶ", qwertyLetter: "7" },
  Digit8: { title: "Patah", letter: "ַ", qwertyLetter: "8" },
  Digit9: { title: "Qamats", letter: "ָ", qwertyLetter: "9" },
  Digit0: { title: "Holam", letter: "ֹ", qwertyLetter: "0" },
  Minus: { title: "Dagesh or Mapiq", letter: "ּ", qwertyLetter: "-" },
  Equal: { title: "Sin Dot", letter: "ׂ", qwertyLetter: "=" },

  KeyQ: { title: "Kuf", letter: "ק", qwertyLetter: "Q" },
  KeyW: { title: "Resh", letter: "ר", qwertyLetter: "W" },
  KeyE: { title: "Alef", letter: "א", qwertyLetter: "E" },
  KeyR: { title: "Tet", letter: "ט", qwertyLetter: "R" },
  KeyT: { title: "Vav", letter: "ו", qwertyLetter: "T" },
  KeyY: { title: "Final Nun", letter: "ן", qwertyLetter: "Y" },
  KeyU: { title: "Final Mem", letter: "ם", qwertyLetter: "U" },
  KeyI: { title: "Pe", letter: "פ", qwertyLetter: "I" },
  KeyO: { title: "Shin", letter: "ש", qwertyLetter: "O" },
  KeyP: { title: "Dalet", letter: "ד", qwertyLetter: "P" },
  
  KeyA: { title: "Gimel", letter: "ג", qwertyLetter: "A" },
  KeyS: { title: "Kaf", letter: "כ", qwertyLetter: "S" },
  KeyD: { title: "Ayin", letter: "ע", qwertyLetter: "D" },
  KeyF: { title: "Yod", letter: "י", qwertyLetter: "F" },
  KeyG: { title: "Het", letter: "ח", qwertyLetter: "G" },
  KeyH: { title: "Lamed", letter: "ל", qwertyLetter: "H" },
  KeyJ: { title: "Final Kaf", letter: "ך", qwertyLetter: "J" },
  KeyK: { title: "Final Pe", letter: "ף", qwertyLetter: "K" },
  KeyL: { title: "Zayin", letter: "ז", qwertyLetter: "L" },
  Semicolon: { title: "Samekh", letter: "ס", qwertyLetter: ";" },

  KeyZ: { title: "Bet", letter: "ב", qwertyLetter: "Z" },
  KeyX: { title: "He", letter: "ה", qwertyLetter: "X" },
  KeyC: { title: "Nun", letter: "נ", qwertyLetter: "C" },
  KeyV: { title: "Mem", letter: "מ", qwertyLetter: "V" },
  KeyB: { title: "Tsadi", letter: "צ", qwertyLetter: "B" },
  KeyN: { title: "Tav", letter: "ת", qwertyLetter: "N" },
  KeyM: { title: "Final Tsadi", letter: "ץ", qwertyLetter: "M" },
}
