const vowels = [
  { title: "Sheva", dataKey: "Digit1", letter: "ְ", qwertyLetter: "1" },
  { title: "Hataf Segol", dataKey: "Digit2", letter: "ֱ", qwertyLetter: "2" },
  { title: "Hataf Patah", dataKey: "Digit3", letter: "ֲ", qwertyLetter: "3" },
  { title: "Hataf Qamats", dataKey: "Digit4", letter: "ֳ", qwertyLetter: "4" },
  { title: "Hiriq", dataKey: "Digit5", letter: "ִ", qwertyLetter: "5" },
  { title: "Tsere", dataKey: "Digit6", letter: "ֵ", qwertyLetter: "6" },
  { title: "Segol", dataKey: "Digit7", letter: "ֶ", qwertyLetter: "7" },
  { title: "Patah", dataKey: "Digit8", letter: "ַ", qwertyLetter: "8" },
  { title: "Qamats", dataKey: "Digit9", letter: "ָ", qwertyLetter: "9" },
  { title: "Holam", dataKey: "Digit0", letter: "ֹ", qwertyLetter: "0" },
  { title: "Dagesh or Mapiq", dataKey: "Minus", letter: "ּ", qwertyLetter: "-" },
  { title: "Sin Dot", dataKey: "Equal", letter: "ׂ", qwertyLetter: "=" },
]

const consonants = [
  { title: "Kuf", dataKey: "KeyQ", letter: "ק", qwertyLetter: "Q" },
  { title: "Resh", dataKey: "KeyW", letter: "ר", qwertyLetter: "W" },
  { title: "Alef", dataKey: "KeyE", letter: "א", qwertyLetter: "E" },
  { title: "Tet", dataKey: "KeyR", letter: "ט", qwertyLetter: "R" },
  { title: "Vav", dataKey: "KeyT", letter: "ו", qwertyLetter: "T" },
  { title: "Final Nun", dataKey: "KeyY", letter: "ן", qwertyLetter: "Y" },
  { title: "Final Mem", dataKey: "KeyU", letter: "ם", qwertyLetter: "U" },
  { title: "Pe", dataKey: "KeyI", letter: "פ", qwertyLetter: "I" },
  { title: "Shin", dataKey: "KeyO", letter: "ש", qwertyLetter: "O" },
  { title: "Dalet", dataKey: "KeyP", letter: "ד", qwertyLetter: "P" },
  { title: "Gimel", dataKey: "KeyA", letter: "ג", qwertyLetter: "A" },
  { title: "Kaf", dataKey: "KeyS", letter: "כ", qwertyLetter: "S" },
  { title: "Ayin", dataKey: "KeyD", letter: "ע", qwertyLetter: "D" },
  { title: "Yod", dataKey: "KeyF", letter: "י", qwertyLetter: "F" },
  { title: "Het", dataKey: "KeyG", letter: "ח", qwertyLetter: "G" },
  { title: "Lamed", dataKey: "KeyH", letter: "ל", qwertyLetter: "H" },
  { title: "Final Kaf", dataKey: "KeyJ", letter: "ך", qwertyLetter: "J" },
  { title: "Final Pe", dataKey: "KeyK", letter: "ף", qwertyLetter: "K" },
  { title: "Zayin", dataKey: "KeyL", letter: "ז", qwertyLetter: "L" },
  { title: "Samekh", dataKey: "Semicolon", letter: "ס", qwertyLetter: ";" },
  { title: "Bet", dataKey: "KeyZ", letter: "ב", qwertyLetter: "Z" },
  { title: "He", dataKey: "KeyX", letter: "ה", qwertyLetter: "X" },
  { title: "Nun", dataKey: "KeyC", letter: "נ", qwertyLetter: "C" },
  { title: "Mem", dataKey: "KeyV", letter: "מ", qwertyLetter: "V" },
  { title: "Tsadi", dataKey: "KeyB", letter: "צ", qwertyLetter: "B" },
  { title: "Tav", dataKey: "KeyN", letter: "ת", qwertyLetter: "N" },
  { title: "Final Tsadi", dataKey: "KeyM", letter: "ץ", qwertyLetter: "M" },
]

export const standardFlatLayout = { vowels: vowels, consonants: consonants }
