export const aramaicLayout = {
  Digit1: { title: "blank", letter: "blank", qwertyLetter: "1" },
  Digit2: { title: "blank", letter: "blank", qwertyLetter: "2" },
  Digit3: { title: "blank", letter: "blank", qwertyLetter: "3" },
  Digit4: { title: "blank", letter: "blank", qwertyLetter: "4" },
  Digit5: { title: "blank", letter: "blank", qwertyLetter: "5" },
  Digit6: { title: "blank", letter: "blank", qwertyLetter: "6" },
  Digit7: { title: "blank", letter: "blank", qwertyLetter: "7" },
  Digit8: { title: "blank", letter: "blank", qwertyLetter: "8" },
  Digit9: { title: "blank", letter: "blank", qwertyLetter: "9" },
  Digit0: { title: "blank", letter: "blank", qwertyLetter: "0" },
  Minus: { title: "blank", letter: "blank", qwertyLetter: "-" },
  Equal: { title: "blank", letter: "blank", qwertyLetter: "=" },

  KeyQ: { title: "blank", letter: "blank", qwertyLetter: "Q" },
  KeyW: { title: "blank", letter: "blank", qwertyLetter: "W" },
  KeyE: { title: "Qoph", letter: "ܩ", qwertyLetter: "E" },
  KeyR: { title: "Resh", letter: "ܪ", qwertyLetter: "R" },
  KeyT: { title: "Aleph", letter: "ܐ", qwertyLetter: "T" },
  KeyY: { title: "Tet", letter: "ܛ", qwertyLetter: "Y" },
  KeyU: { title: "Waw", letter: "ܘ", qwertyLetter: "U" },
  KeyI: { title: "Taw", letter: "ܬ", qwertyLetter: "I" },
  KeyO: { title: "blank", letter: "blank", qwertyLetter: "O" },
  KeyP: { title: "Peh", letter: "ܦ", qwertyLetter: "P" },

  KeyA: { title: "Shin", letter: "ܫ", qwertyLetter: "A" },
  KeyS: { title: "Dalet", letter: "ܕ", qwertyLetter: "S" },
  KeyD: { title: "Gimel", letter: "ܓ", qwertyLetter: "D" },
  KeyF: { title: "Kaph", letter: "ܟ", qwertyLetter: "F" },
  KeyG: { title: "Ayin", letter: "ܥ", qwertyLetter: "G" },
  KeyH: { title: "Yodh", letter: "ܝ", qwertyLetter: "H" },
  KeyJ: { title: "Heth", letter: "ܚ", qwertyLetter: "J" },
  KeyK: { title: "Lamedh", letter: "ܠ", qwertyLetter: "K" },
  KeyL: { title: "blank", letter: "blank", qwertyLetter: "L" },
  Semicolon: { title: "blank", letter: "blank", qwertyLetter: ";" },

  KeyZ: { title: "Zayin", letter: "ܙ", qwertyLetter: "Z" },
  KeyX: { title: "Samekh", letter: "ܣ", qwertyLetter: "X" },
  KeyC: { title: "Bet", letter: "ܒ", qwertyLetter: "C" },
  KeyV: { title: "He", letter: "ܗ", qwertyLetter: "V" },
  KeyB: { title: "Nun", letter: "ܢ", qwertyLetter: "B" },
  KeyN: { title: "Mem", letter: "ܡ", qwertyLetter: "N" },
  KeyM: { title: "Tsade", letter: "ܨ", qwertyLetter: "M" },
};
